server {
  listen 8080;
  server_name _;

  location = /healthz {
    access_log off;
    default_type application/json;
    return 200 '{"status":"healthy"}';
  }

  location / {
    default_type application/json;
    return 200 '{"service":"app02-service","status":"healthy"}';
  }
}
